services:

        postgresdb:
                image: postgres:16.2-alpine3.19
                volumes:
                        - postgres-db-volume-kafka:/var/lib/postgresql/data
                env_file:
                        - ./docker-secrets


                ports:
                        - 54321:5432
volumes:
        postgres-db-volume-kafka:
